### ISSUE TITLE
Feature request: More detailed SMTP activity logging

### ISSUE THREAD

**Issue by GitHipster** [Raikia/FiercePhish#19]
Feature request: More detailed SMTP activity logging

**Comment by Raikia** [comment]
What logs are you talking about?  Like having direct access to /var/log/mail.log?  Or something more in-depth?

**Comment by GitHipster** [comment]
A bit of both. More detailed output would be useful. Maybe by adding this on the 'E-mail Details' page when clicking on a mail in the E-mail Log page. For instance you could see errors like these: postfix/smtpd[30679]: warning: connect to Milter service inet:localhost:12301: Connection refused

Als a web view with download button of the mail.log file would be nice.

**Comment by Raikia** [comment]
This is a work-in-progress:

![img](https://vgy.me/sDQrHU.png)

and on each email-details page:

![img](https://vgy.me/owftBm.png)


Is there more functionality you would like to see for this feature?

**Comment by GitHipster** [comment]
Looking good Chris. A counter or graph per mail domain would be nice. An color coding. Info messages green /blue, warnings orange and errors red?

**Comment by Raikia** [comment]
I think color coding might be a decent future enhancement, but its a bit more effort then I think this should have right now at least.  It's somewhat difficult to consistently parse for errors or not because of so many different possible error messages from postfix.  We'll see how this feature works out and if color-coding is necessary in the future, it may be added.

**Comment by Raikia** [comment]
This was included in the [v1.2.0 release](https://github.com/Raikia/FiercePhish/releases/tag/v1.2.0).  Issue resolved.

**Comment by GitHipster** [comment]
Great, thanks!
