### ISSUE TITLE
Officially support Kali ?

### ISSUE THREAD

**Issue by rami418** [Raikia/FiercePhish#50]
Hi !

Can/Will FiercePhish be officially supported on kali linux soon ?

Thank you very much ;)

**Comment by Raikia** [comment]
FiercePhish is intended to be a throwaway install on a cloud system (or internet-facing host) to conduct phishing engagements from.  Kali is not a hardened system and should not be internet-facing for multiple reasons.  Additionally, FiercePhish installs some dependencies that you probably don't want on your Kali install (like a configured mail server).

For these reasons, I am not _planning_ on supporting Kali because there isn't really a use-case for using it on Kali.  I do have plans to support other operating systems though, such as Debian, Fedora, etc.  Maybe I can fit Kali in there, but we'll see.  As I said, it's really not intended to be used on Kali unless you can provide me a good use-case of it.

That said, it _definitely_ does run on Kali with no issues.  You just have to follow the [Manual Installation Guide](https://github.com/Raikia/FiercePhish/wiki/Manual-Installation-Guide-(FiercePhish))
