### ISSUE TITLE
Bug: Email send queue plays "catch-up" if send time is set to point in the past.

### ISSUE THREAD

**Issue by ad0nis** [Raikia/FiercePhish#52]
If you are configuring a campaign, and use the delay functionality, and the time isn’t sent to a point in the future, it will do math from the point where it should have started to now, and play catch-up. Sent 90 emails immediately instead of doing 30 every 2 minutes.

**Comment by Raikia** [comment]
Is this really a bug?  I feel like this is expected behavior...?  Why/how did you set the "start time" to a time in the past?  The UI should default to basically "now" and only show time/dates in the future.  I suppose if you sit on that Create Campaign page for a couple minutes, that could cause this from happening....but I'm interested in hearing what you came across.

I suppose I can force it to use "now" time if the time is in the past.  Thoughts?  I'd like more information about your specific case though

**Comment by ad0nis** [comment]
You are correct on your assumption of me sitting on the Create Campaign button for multiple minutes. Just double and triple-checking everything to make sure there are no mistakes in the campaign. I think your proposed solution sounds ideal.
