### ISSUE TITLE
Target Import non-functioning

### ISSUE THREAD

**Issue by housemusic42** [Raikia/FiercePhish#87]
Hello, 

No sure if this is still being maintained but I'm having an issue importing a target list. 

I followed the wiki example and even tried a fresh install. The laravel logs aren't showing anything failing, the job shows up in the queue, says successful but nothing ever shows up. 

I've worked around it by just using a mysqlimport but would like to demonstrate the functionality through the web ui. 

Thanks!

**Comment by Raikia** [comment]
Stupidly this is a recent issue due to an update in Ubuntu.  I need to fix the installer, but the current work-around is:

1. Edit "/etc/systemd/system/multi-user.target.wants/apache2.service"
2. Put "PrivateTmp=false" under the "[Service]" category:
![asdf](https://i.imgur.com/eaJAC8v.png)
3. Restart Apache:  "service apache2 restart"

**Comment by housemusic42** [comment]
boom goes the dynamite!

thanks for the response, everything is now importing!

**Comment by Raikia** [comment]
Keeping this open so others can find it since its not fixed in master yet :-)

**Comment by Raikia** [comment]
This is officially fixed and merged
